server:
  port: 9000
eureka:
  server:
    enable-self-preservation: false
  instance:
      hostname: eureka
  client:
    service-url:
      defaultZone: http://eureka:9000/eureka
    #是否需要将自己注册到注册中心(注册中心集群需要设置为true)
    register-with-eureka: false
    #是否需要搜索服务信息 因为自己是注册中心所以为false
    fetch-registry: false