package com.china315net.serviceactivity.Entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class tjactivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public tjactivityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAnameIsNull() {
            addCriterion("AName is null");
            return (Criteria) this;
        }

        public Criteria andAnameIsNotNull() {
            addCriterion("AName is not null");
            return (Criteria) this;
        }

        public Criteria andAnameEqualTo(String value) {
            addCriterion("AName =", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotEqualTo(String value) {
            addCriterion("AName <>", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameGreaterThan(String value) {
            addCriterion("AName >", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameGreaterThanOrEqualTo(String value) {
            addCriterion("AName >=", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLessThan(String value) {
            addCriterion("AName <", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLessThanOrEqualTo(String value) {
            addCriterion("AName <=", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameLike(String value) {
            addCriterion("AName like", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotLike(String value) {
            addCriterion("AName not like", value, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameIn(List<String> values) {
            addCriterion("AName in", values, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotIn(List<String> values) {
            addCriterion("AName not in", values, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameBetween(String value1, String value2) {
            addCriterion("AName between", value1, value2, "aname");
            return (Criteria) this;
        }

        public Criteria andAnameNotBetween(String value1, String value2) {
            addCriterion("AName not between", value1, value2, "aname");
            return (Criteria) this;
        }

        public Criteria andStmIsNull() {
            addCriterion("STM is null");
            return (Criteria) this;
        }

        public Criteria andStmIsNotNull() {
            addCriterion("STM is not null");
            return (Criteria) this;
        }

        public Criteria andStmEqualTo(Date value) {
            addCriterion("STM =", value, "stm");
            return (Criteria) this;
        }

        public Criteria andStmNotEqualTo(Date value) {
            addCriterion("STM <>", value, "stm");
            return (Criteria) this;
        }

        public Criteria andStmGreaterThan(Date value) {
            addCriterion("STM >", value, "stm");
            return (Criteria) this;
        }

        public Criteria andStmGreaterThanOrEqualTo(Date value) {
            addCriterion("STM >=", value, "stm");
            return (Criteria) this;
        }

        public Criteria andStmLessThan(Date value) {
            addCriterion("STM <", value, "stm");
            return (Criteria) this;
        }

        public Criteria andStmLessThanOrEqualTo(Date value) {
            addCriterion("STM <=", value, "stm");
            return (Criteria) this;
        }

        public Criteria andStmIn(List<Date> values) {
            addCriterion("STM in", values, "stm");
            return (Criteria) this;
        }

        public Criteria andStmNotIn(List<Date> values) {
            addCriterion("STM not in", values, "stm");
            return (Criteria) this;
        }

        public Criteria andStmBetween(Date value1, Date value2) {
            addCriterion("STM between", value1, value2, "stm");
            return (Criteria) this;
        }

        public Criteria andStmNotBetween(Date value1, Date value2) {
            addCriterion("STM not between", value1, value2, "stm");
            return (Criteria) this;
        }

        public Criteria andEtmIsNull() {
            addCriterion("ETM is null");
            return (Criteria) this;
        }

        public Criteria andEtmIsNotNull() {
            addCriterion("ETM is not null");
            return (Criteria) this;
        }

        public Criteria andEtmEqualTo(Date value) {
            addCriterion("ETM =", value, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmNotEqualTo(Date value) {
            addCriterion("ETM <>", value, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmGreaterThan(Date value) {
            addCriterion("ETM >", value, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmGreaterThanOrEqualTo(Date value) {
            addCriterion("ETM >=", value, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmLessThan(Date value) {
            addCriterion("ETM <", value, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmLessThanOrEqualTo(Date value) {
            addCriterion("ETM <=", value, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmIn(List<Date> values) {
            addCriterion("ETM in", values, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmNotIn(List<Date> values) {
            addCriterion("ETM not in", values, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmBetween(Date value1, Date value2) {
            addCriterion("ETM between", value1, value2, "etm");
            return (Criteria) this;
        }

        public Criteria andEtmNotBetween(Date value1, Date value2) {
            addCriterion("ETM not between", value1, value2, "etm");
            return (Criteria) this;
        }

        public Criteria andObcodetypeIsNull() {
            addCriterion("ObCodeType is null");
            return (Criteria) this;
        }

        public Criteria andObcodetypeIsNotNull() {
            addCriterion("ObCodeType is not null");
            return (Criteria) this;
        }

        public Criteria andObcodetypeEqualTo(String value) {
            addCriterion("ObCodeType =", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeNotEqualTo(String value) {
            addCriterion("ObCodeType <>", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeGreaterThan(String value) {
            addCriterion("ObCodeType >", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeGreaterThanOrEqualTo(String value) {
            addCriterion("ObCodeType >=", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeLessThan(String value) {
            addCriterion("ObCodeType <", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeLessThanOrEqualTo(String value) {
            addCriterion("ObCodeType <=", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeLike(String value) {
            addCriterion("ObCodeType like", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeNotLike(String value) {
            addCriterion("ObCodeType not like", value, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeIn(List<String> values) {
            addCriterion("ObCodeType in", values, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeNotIn(List<String> values) {
            addCriterion("ObCodeType not in", values, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeBetween(String value1, String value2) {
            addCriterion("ObCodeType between", value1, value2, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andObcodetypeNotBetween(String value1, String value2) {
            addCriterion("ObCodeType not between", value1, value2, "obcodetype");
            return (Criteria) this;
        }

        public Criteria andAsidIsNull() {
            addCriterion("ASID is null");
            return (Criteria) this;
        }

        public Criteria andAsidIsNotNull() {
            addCriterion("ASID is not null");
            return (Criteria) this;
        }

        public Criteria andAsidEqualTo(Integer value) {
            addCriterion("ASID =", value, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidNotEqualTo(Integer value) {
            addCriterion("ASID <>", value, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidGreaterThan(Integer value) {
            addCriterion("ASID >", value, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ASID >=", value, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidLessThan(Integer value) {
            addCriterion("ASID <", value, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidLessThanOrEqualTo(Integer value) {
            addCriterion("ASID <=", value, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidIn(List<Integer> values) {
            addCriterion("ASID in", values, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidNotIn(List<Integer> values) {
            addCriterion("ASID not in", values, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidBetween(Integer value1, Integer value2) {
            addCriterion("ASID between", value1, value2, "asid");
            return (Criteria) this;
        }

        public Criteria andAsidNotBetween(Integer value1, Integer value2) {
            addCriterion("ASID not between", value1, value2, "asid");
            return (Criteria) this;
        }

        public Criteria andCompidIsNull() {
            addCriterion("CompID is null");
            return (Criteria) this;
        }

        public Criteria andCompidIsNotNull() {
            addCriterion("CompID is not null");
            return (Criteria) this;
        }

        public Criteria andCompidEqualTo(Integer value) {
            addCriterion("CompID =", value, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidNotEqualTo(Integer value) {
            addCriterion("CompID <>", value, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidGreaterThan(Integer value) {
            addCriterion("CompID >", value, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CompID >=", value, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidLessThan(Integer value) {
            addCriterion("CompID <", value, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidLessThanOrEqualTo(Integer value) {
            addCriterion("CompID <=", value, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidIn(List<Integer> values) {
            addCriterion("CompID in", values, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidNotIn(List<Integer> values) {
            addCriterion("CompID not in", values, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidBetween(Integer value1, Integer value2) {
            addCriterion("CompID between", value1, value2, "compid");
            return (Criteria) this;
        }

        public Criteria andCompidNotBetween(Integer value1, Integer value2) {
            addCriterion("CompID not between", value1, value2, "compid");
            return (Criteria) this;
        }

        public Criteria andCreateidIsNull() {
            addCriterion("CreateID is null");
            return (Criteria) this;
        }

        public Criteria andCreateidIsNotNull() {
            addCriterion("CreateID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateidEqualTo(Integer value) {
            addCriterion("CreateID =", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotEqualTo(Integer value) {
            addCriterion("CreateID <>", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidGreaterThan(Integer value) {
            addCriterion("CreateID >", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CreateID >=", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLessThan(Integer value) {
            addCriterion("CreateID <", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidLessThanOrEqualTo(Integer value) {
            addCriterion("CreateID <=", value, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidIn(List<Integer> values) {
            addCriterion("CreateID in", values, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotIn(List<Integer> values) {
            addCriterion("CreateID not in", values, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidBetween(Integer value1, Integer value2) {
            addCriterion("CreateID between", value1, value2, "createid");
            return (Criteria) this;
        }

        public Criteria andCreateidNotBetween(Integer value1, Integer value2) {
            addCriterion("CreateID not between", value1, value2, "createid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CreateDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CreateDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CreateDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CreateDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CreateDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CreateDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CreateDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CreateDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CreateDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CreateDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("Remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("Remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("Remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("Remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("Remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("Remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("Remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("Remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("Remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("Remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("Remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("Remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("Remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("Remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andYzmIsNull() {
            addCriterion("YZM is null");
            return (Criteria) this;
        }

        public Criteria andYzmIsNotNull() {
            addCriterion("YZM is not null");
            return (Criteria) this;
        }

        public Criteria andYzmEqualTo(Byte value) {
            addCriterion("YZM =", value, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmNotEqualTo(Byte value) {
            addCriterion("YZM <>", value, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmGreaterThan(Byte value) {
            addCriterion("YZM >", value, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmGreaterThanOrEqualTo(Byte value) {
            addCriterion("YZM >=", value, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmLessThan(Byte value) {
            addCriterion("YZM <", value, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmLessThanOrEqualTo(Byte value) {
            addCriterion("YZM <=", value, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmIn(List<Byte> values) {
            addCriterion("YZM in", values, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmNotIn(List<Byte> values) {
            addCriterion("YZM not in", values, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmBetween(Byte value1, Byte value2) {
            addCriterion("YZM between", value1, value2, "yzm");
            return (Criteria) this;
        }

        public Criteria andYzmNotBetween(Byte value1, Byte value2) {
            addCriterion("YZM not between", value1, value2, "yzm");
            return (Criteria) this;
        }

        public Criteria andFacetoIsNull() {
            addCriterion("FaceTo is null");
            return (Criteria) this;
        }

        public Criteria andFacetoIsNotNull() {
            addCriterion("FaceTo is not null");
            return (Criteria) this;
        }

        public Criteria andFacetoEqualTo(Integer value) {
            addCriterion("FaceTo =", value, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoNotEqualTo(Integer value) {
            addCriterion("FaceTo <>", value, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoGreaterThan(Integer value) {
            addCriterion("FaceTo >", value, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoGreaterThanOrEqualTo(Integer value) {
            addCriterion("FaceTo >=", value, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoLessThan(Integer value) {
            addCriterion("FaceTo <", value, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoLessThanOrEqualTo(Integer value) {
            addCriterion("FaceTo <=", value, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoIn(List<Integer> values) {
            addCriterion("FaceTo in", values, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoNotIn(List<Integer> values) {
            addCriterion("FaceTo not in", values, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoBetween(Integer value1, Integer value2) {
            addCriterion("FaceTo between", value1, value2, "faceto");
            return (Criteria) this;
        }

        public Criteria andFacetoNotBetween(Integer value1, Integer value2) {
            addCriterion("FaceTo not between", value1, value2, "faceto");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentIsNull() {
            addCriterion("feedbacktoparent is null");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentIsNotNull() {
            addCriterion("feedbacktoparent is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentEqualTo(Integer value) {
            addCriterion("feedbacktoparent =", value, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentNotEqualTo(Integer value) {
            addCriterion("feedbacktoparent <>", value, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentGreaterThan(Integer value) {
            addCriterion("feedbacktoparent >", value, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedbacktoparent >=", value, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentLessThan(Integer value) {
            addCriterion("feedbacktoparent <", value, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentLessThanOrEqualTo(Integer value) {
            addCriterion("feedbacktoparent <=", value, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentIn(List<Integer> values) {
            addCriterion("feedbacktoparent in", values, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentNotIn(List<Integer> values) {
            addCriterion("feedbacktoparent not in", values, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentBetween(Integer value1, Integer value2) {
            addCriterion("feedbacktoparent between", value1, value2, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedbacktoparentNotBetween(Integer value1, Integer value2) {
            addCriterion("feedbacktoparent not between", value1, value2, "feedbacktoparent");
            return (Criteria) this;
        }

        public Criteria andFeedvalueIsNull() {
            addCriterion("feedvalue is null");
            return (Criteria) this;
        }

        public Criteria andFeedvalueIsNotNull() {
            addCriterion("feedvalue is not null");
            return (Criteria) this;
        }

        public Criteria andFeedvalueEqualTo(Integer value) {
            addCriterion("feedvalue =", value, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueNotEqualTo(Integer value) {
            addCriterion("feedvalue <>", value, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueGreaterThan(Integer value) {
            addCriterion("feedvalue >", value, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedvalue >=", value, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueLessThan(Integer value) {
            addCriterion("feedvalue <", value, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueLessThanOrEqualTo(Integer value) {
            addCriterion("feedvalue <=", value, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueIn(List<Integer> values) {
            addCriterion("feedvalue in", values, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueNotIn(List<Integer> values) {
            addCriterion("feedvalue not in", values, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueBetween(Integer value1, Integer value2) {
            addCriterion("feedvalue between", value1, value2, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andFeedvalueNotBetween(Integer value1, Integer value2) {
            addCriterion("feedvalue not between", value1, value2, "feedvalue");
            return (Criteria) this;
        }

        public Criteria andKhddhIsNull() {
            addCriterion("khddh is null");
            return (Criteria) this;
        }

        public Criteria andKhddhIsNotNull() {
            addCriterion("khddh is not null");
            return (Criteria) this;
        }

        public Criteria andKhddhEqualTo(String value) {
            addCriterion("khddh =", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhNotEqualTo(String value) {
            addCriterion("khddh <>", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhGreaterThan(String value) {
            addCriterion("khddh >", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhGreaterThanOrEqualTo(String value) {
            addCriterion("khddh >=", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhLessThan(String value) {
            addCriterion("khddh <", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhLessThanOrEqualTo(String value) {
            addCriterion("khddh <=", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhLike(String value) {
            addCriterion("khddh like", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhNotLike(String value) {
            addCriterion("khddh not like", value, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhIn(List<String> values) {
            addCriterion("khddh in", values, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhNotIn(List<String> values) {
            addCriterion("khddh not in", values, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhBetween(String value1, String value2) {
            addCriterion("khddh between", value1, value2, "khddh");
            return (Criteria) this;
        }

        public Criteria andKhddhNotBetween(String value1, String value2) {
            addCriterion("khddh not between", value1, value2, "khddh");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateIsNull() {
            addCriterion("anyfahuodate is null");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateIsNotNull() {
            addCriterion("anyfahuodate is not null");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateEqualTo(Integer value) {
            addCriterion("anyfahuodate =", value, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateNotEqualTo(Integer value) {
            addCriterion("anyfahuodate <>", value, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateGreaterThan(Integer value) {
            addCriterion("anyfahuodate >", value, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateGreaterThanOrEqualTo(Integer value) {
            addCriterion("anyfahuodate >=", value, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateLessThan(Integer value) {
            addCriterion("anyfahuodate <", value, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateLessThanOrEqualTo(Integer value) {
            addCriterion("anyfahuodate <=", value, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateIn(List<Integer> values) {
            addCriterion("anyfahuodate in", values, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateNotIn(List<Integer> values) {
            addCriterion("anyfahuodate not in", values, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateBetween(Integer value1, Integer value2) {
            addCriterion("anyfahuodate between", value1, value2, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andAnyfahuodateNotBetween(Integer value1, Integer value2) {
            addCriterion("anyfahuodate not between", value1, value2, "anyfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateIsNull() {
            addCriterion("sfahuodate is null");
            return (Criteria) this;
        }

        public Criteria andSfahuodateIsNotNull() {
            addCriterion("sfahuodate is not null");
            return (Criteria) this;
        }

        public Criteria andSfahuodateEqualTo(Date value) {
            addCriterion("sfahuodate =", value, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateNotEqualTo(Date value) {
            addCriterion("sfahuodate <>", value, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateGreaterThan(Date value) {
            addCriterion("sfahuodate >", value, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateGreaterThanOrEqualTo(Date value) {
            addCriterion("sfahuodate >=", value, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateLessThan(Date value) {
            addCriterion("sfahuodate <", value, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateLessThanOrEqualTo(Date value) {
            addCriterion("sfahuodate <=", value, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateIn(List<Date> values) {
            addCriterion("sfahuodate in", values, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateNotIn(List<Date> values) {
            addCriterion("sfahuodate not in", values, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateBetween(Date value1, Date value2) {
            addCriterion("sfahuodate between", value1, value2, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andSfahuodateNotBetween(Date value1, Date value2) {
            addCriterion("sfahuodate not between", value1, value2, "sfahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateIsNull() {
            addCriterion("efahuodate is null");
            return (Criteria) this;
        }

        public Criteria andEfahuodateIsNotNull() {
            addCriterion("efahuodate is not null");
            return (Criteria) this;
        }

        public Criteria andEfahuodateEqualTo(Date value) {
            addCriterion("efahuodate =", value, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateNotEqualTo(Date value) {
            addCriterion("efahuodate <>", value, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateGreaterThan(Date value) {
            addCriterion("efahuodate >", value, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateGreaterThanOrEqualTo(Date value) {
            addCriterion("efahuodate >=", value, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateLessThan(Date value) {
            addCriterion("efahuodate <", value, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateLessThanOrEqualTo(Date value) {
            addCriterion("efahuodate <=", value, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateIn(List<Date> values) {
            addCriterion("efahuodate in", values, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateNotIn(List<Date> values) {
            addCriterion("efahuodate not in", values, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateBetween(Date value1, Date value2) {
            addCriterion("efahuodate between", value1, value2, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andEfahuodateNotBetween(Date value1, Date value2) {
            addCriterion("efahuodate not between", value1, value2, "efahuodate");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andTpIsNull() {
            addCriterion("tp is null");
            return (Criteria) this;
        }

        public Criteria andTpIsNotNull() {
            addCriterion("tp is not null");
            return (Criteria) this;
        }

        public Criteria andTpEqualTo(String value) {
            addCriterion("tp =", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpNotEqualTo(String value) {
            addCriterion("tp <>", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpGreaterThan(String value) {
            addCriterion("tp >", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpGreaterThanOrEqualTo(String value) {
            addCriterion("tp >=", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpLessThan(String value) {
            addCriterion("tp <", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpLessThanOrEqualTo(String value) {
            addCriterion("tp <=", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpLike(String value) {
            addCriterion("tp like", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpNotLike(String value) {
            addCriterion("tp not like", value, "tp");
            return (Criteria) this;
        }

        public Criteria andTpIn(List<String> values) {
            addCriterion("tp in", values, "tp");
            return (Criteria) this;
        }

        public Criteria andTpNotIn(List<String> values) {
            addCriterion("tp not in", values, "tp");
            return (Criteria) this;
        }

        public Criteria andTpBetween(String value1, String value2) {
            addCriterion("tp between", value1, value2, "tp");
            return (Criteria) this;
        }

        public Criteria andTpNotBetween(String value1, String value2) {
            addCriterion("tp not between", value1, value2, "tp");
            return (Criteria) this;
        }

        public Criteria andIsopenIsNull() {
            addCriterion("isopen is null");
            return (Criteria) this;
        }

        public Criteria andIsopenIsNotNull() {
            addCriterion("isopen is not null");
            return (Criteria) this;
        }

        public Criteria andIsopenEqualTo(Byte value) {
            addCriterion("isopen =", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenNotEqualTo(Byte value) {
            addCriterion("isopen <>", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenGreaterThan(Byte value) {
            addCriterion("isopen >", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenGreaterThanOrEqualTo(Byte value) {
            addCriterion("isopen >=", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenLessThan(Byte value) {
            addCriterion("isopen <", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenLessThanOrEqualTo(Byte value) {
            addCriterion("isopen <=", value, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenIn(List<Byte> values) {
            addCriterion("isopen in", values, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenNotIn(List<Byte> values) {
            addCriterion("isopen not in", values, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenBetween(Byte value1, Byte value2) {
            addCriterion("isopen between", value1, value2, "isopen");
            return (Criteria) this;
        }

        public Criteria andIsopenNotBetween(Byte value1, Byte value2) {
            addCriterion("isopen not between", value1, value2, "isopen");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Byte value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Byte value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Byte value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Byte value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Byte> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Byte> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Byte value1, Byte value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tj_activity
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tj_activity
     *
     * @mbg.generated Mon Jan 11 15:55:06 GMT+08:00 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}